export class Familia{
  idDatoFamilia:string;
  idEmpresa:string;
  idPostulante:string;
  idTipoDocumentoIdentidad:string;
  numeroDocumento:string;
  apellidoPaterno:string;
  apellidoMaterno:string;
  nombres:string;
  idDatoGenero:string;
  idDatoTipoParentesco:string;
  idDatoGradoInstruccion:string;
  ocupacion:string;
  fechaNacimiento:Date;
  idDatoPaisNacimiento:string;
  idDptoNacimiento:string;
  idProvNacimiento:string;
  idDistNacimiento:string;
}
